package io.github.vrcmteam.vrcm.presentation.theme.pink
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8B4A61)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD9E3)
val onPrimaryContainerLight = Color(0xFF3A071E)
val secondaryLight = Color(0xFF74565F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD9E3)
val onSecondaryContainerLight = Color(0xFF2B151C)
val tertiaryLight = Color(0xFF7D5635)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDCC2)
val onTertiaryContainerLight = Color(0xFF2E1500)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F8)
val onBackgroundLight = Color(0xFF22191C)
val surfaceLight = Color(0xFFFFF8F8)
val onSurfaceLight = Color(0xFF22191C)
val surfaceVariantLight = Color(0xFFF2DDE2)
val onSurfaceVariantLight = Color(0xFF514347)
val outlineLight = Color(0xFF837377)
val outlineVariantLight = Color(0xFFD5C2C6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372E30)
val inverseOnSurfaceLight = Color(0xFFFDEDF0)
val inversePrimaryLight = Color(0xFFFFB0C9)
val surfaceDimLight = Color(0xFFE6D6D9)
val surfaceBrightLight = Color(0xFFFFF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F2)
val surfaceContainerLight = Color(0xFFFAEAED)
val surfaceContainerHighLight = Color(0xFFF5E4E7)
val surfaceContainerHighestLight = Color(0xFFEFDFE2)

val primaryDark = Color(0xFFFFB0C9)
val onPrimaryDark = Color(0xFF541D33)
val primaryContainerDark = Color(0xFF6F334A)
val onPrimaryContainerDark = Color(0xFFFFD9E3)
val secondaryDark = Color(0xFFE2BDC7)
val onSecondaryDark = Color(0xFF422931)
val secondaryContainerDark = Color(0xFF5A3F48)
val onSecondaryContainerDark = Color(0xFFFFD9E3)
val tertiaryDark = Color(0xFFEFBC94)
val onTertiaryDark = Color(0xFF48290C)
val tertiaryContainerDark = Color(0xFF623F20)
val onTertiaryContainerDark = Color(0xFFFFDCC2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191114)
val onBackgroundDark = Color(0xFFEFDFE2)
val surfaceDark = Color(0xFF191114)
val onSurfaceDark = Color(0xFFEFDFE2)
val surfaceVariantDark = Color(0xFF514347)
val onSurfaceVariantDark = Color(0xFFD5C2C6)
val outlineDark = Color(0xFF9E8C90)
val outlineVariantDark = Color(0xFF514347)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFDFE2)
val inverseOnSurfaceDark = Color(0xFF372E30)
val inversePrimaryDark = Color(0xFF8B4A61)
val surfaceDimDark = Color(0xFF191114)
val surfaceBrightDark = Color(0xFF403739)
val surfaceContainerLowestDark = Color(0xFF140C0E)
val surfaceContainerLowDark = Color(0xFF22191C)
val surfaceContainerDark = Color(0xFF261D20)
val surfaceContainerHighDark = Color(0xFF31282A)
val surfaceContainerHighestDark = Color(0xFF3C3235)








